Pull request for mobile first
codehass/Portfolio pull request #1
Opened 2022-10-27 09:00 UTC by codehass

In this Pull request :
- Added Linters
- Added Html file and content
- Added CSS file and styling
- Updated README.md file

 Thank you for reviewing my Pull request.

2022-10-27 09:10 UTC, topeogunleye reviewed
Hi @codehass, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️

   - You have submitted a project that has failing linters, Kindly make sure your linters are all passing before submitting the PR.

## Stlylint AutoFix
- [ ] if you have a lot of CSS line errors, I kindly suggest you fix them by running `npx stylelint --fix "**/*.{css,scss}"` on your command line, but please get used to fixing the errors line by line also because it'll help you learn best practices.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.

2022-10-27 11:00 UTC, nedjwab requested changes
# Changes Required ♻️
### Hi @codehass  

Nice job, you are almost there.

![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## (Highlights) Good Points: :
- Good implementation of some of the project requirements  ✔
- GitHub flow was correctly used ✔.

## (Changes Required) Aspects to improve: ♻️
You did great implementing some of the project requirements, but you still have some issues: 
check the comments below 👇👇👇👇👇
 
## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-10-27 11:00 UTC, nedjwab commented on index.html
> +    <div class="container">
[ ] The container of the section should be a `header` tag. Typically the `header` tag is used as a page header, it contains the site's title or logo (or both) and the main site navigation. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) for more info. kindly fix that 🤓

2022-10-27 11:00 UTC, nedjwab commented on index.html
> +        <img src="/imgs/image_geometry_1.png" alt="image" />
[ ] kindly add the hamburger button to your design, it's part of the requirements.🤓

The Figma design 👇 :
![hamburgerdesign](https://user-images.githubusercontent.com/62156607/198265342-0b9170d1-3eb5-415e-bccf-a21e6f3237bb.PNG)


Your design 👇 : 
![hamburgerta3ou](https://user-images.githubusercontent.com/62156607/198265302-92fc69df-d3e7-4409-9693-f3df66c543bb.PNG)

2022-10-27 11:00 UTC, nedjwab commented on style.css
> +    display: flex;
Nice use of the flex 🔥🔥🔥🔥

2022-10-27 11:00 UTC, nedjwab commented on style.css
> +  .headline-cont button {
[ ] kindly add the hover effect to your button. they are part of the requirements kindly fix that 🤓.
The Figma design👇 :
![buttonhover](https://user-images.githubusercontent.com/62156607/198266896-d30284eb-e4b7-4a06-a6f9-475cc6782c1a.PNG)

2022-10-27 13:53 UTC, Nyame-Wolf requested changes
# STATUS: REQUIRED CHANGES :recycle: 

Hi @codehass  :wave: 

Your project page is looking fantastic so far :star_struck: ! 

However, there is still some room for improvement, that can help you have better code and make your project professional :sunglasses: 

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights :sparkles:

- Great work using the right GitHub Flow :100: 
- Linters are passing
- Project Documentation (PR, README) is professional :necktie: 

Congrats on your work so far! :clap:  

## Required Changes ♻️

There are some issues that you still need to work on to go to the next project, but you are almost there! 
_For more information, check the comments under the review :arrow_down:_

## Optional suggestions :ballot_box_with_check: 

_Every comment with the **[OPTIONAL]** prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can improve the quality of your code :100:_

Happy coding and keep it up! :raised_hands: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
  Please, remember to tag me **@Nyame-Wolf**  in your question so I can receive the notification.

  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

  _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-10-27 13:53 UTC, Nyame-Wolf commented on index.html
> +        <img src="/imgs/ic_menu (1).png" alt="Menu" class="menu-icon" />
[OPTIONAL] Kindly note that this is supposed to be a background image. The previous reviewer might not have highlighted it but please change it as its part of the requirements

2022-10-27 13:53 UTC, Nyame-Wolf commented on index.html
> +        <img src="/imgs/ic_menu (1).png" alt="Menu" class="menu-icon" />
Please fix the paths to your images. Remove the stroke before the path i.e: from 
`<img src="/imgs/ic_menu (1).png" alt="Menu" class="menu-icon" />` to <img src="imgs/ic_menu (1).png" alt="Menu" class="menu-icon" />
This is the current display of your page:
<img width="1675" alt="Screenshot 2022-10-27 at 16 49 33" src="https://user-images.githubusercontent.com/48546992/198302793-40db1d96-6476-4e19-bdcd-e6f57a153b3a.png">

2022-10-27 13:53 UTC, Nyame-Wolf commented on index.html
> +      <img src="/imgs/image_geometry_2.png" class="headline-img" />
[OPTIONAL] Kindly note that this is supposed to be a background image. The previous reviewer might not have highlighted it but please change it as its part of the requirements

2022-10-28 06:10 UTC, sajid-munawar approved these changes
### Hi @codehass , 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and description :heavy_check_mark:
 
 ## [Optional] suggestions:
 * [ ]  Please check my inline comments.

> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @sajid-munawar in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 08:22 UTC, merged